version: '3'
services:
  build:
    build:
      context: .
      dockerfile: build.Dockerfile
    volumes:
      - ../../:/app
    working_dir: /app
    command: bash ./tasks/ci/build
  publish:
    build:
      context: .
      dockerfile: publish.Dockerfile
    volumes:
      - ../../:/app
    working_dir: /app
    environment:
      NPM_TOKEN: ${NPM_TOKEN}
    command: bash ./tasks/ci/publish
  deploy:
    build:
      context: .
      dockerfile: deploy.Dockerfile
    volumes:
      - ../../:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    command: bash ./tasks/ci/deploy
  integration:
    build:
      context: .
      dockerfile: integration.Dockerfile
    volumes:
      - ../../:/app
    working_dir: /app
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    command: bash ./tasks/ci/integration
